### Задание 1. 

In [9]:
import numpy as np

In [11]:
sites = ["GAGGTAAAC", "TCCGTAAGC", "CAGGTTGGA", "ACAGTCAGC", "TAGGTCAGC", "CAGGTCAGC", "CAGGTCGAT", "CAGGTCAGC", "CAGGTCAGC", "CAGGTTGGC"]

In [13]:
def PFM(sites):
    # Преобразуем список строк в двумерный массив символов
    # Каждая строка разбивается на список символов
    seq_array = np.array([list(seq) for seq in sites])
    
    # Задаём порядок нуклеотидов
    nucleotides = ['A', 'T', 'G', 'C']
    
    # Для каждого нуклеотида считаем, сколько раз он встречается в каждой позиции
    pfm = np.array([(seq_array == nuc).sum(axis=0) for nuc in nucleotides])
    
    return pfm

In [15]:
pfm_matrix = PFM(sites)
pfm_matrix

array([[ 1,  8,  1,  0,  0,  2,  7,  2,  1],
       [ 2,  0,  0,  0, 10,  2,  0,  0,  1],
       [ 1,  0,  8, 10,  0,  0,  3,  8,  0],
       [ 6,  2,  1,  0,  0,  6,  0,  0,  8]])

In [31]:
def PFM_to_PPM(sites, pfm_matrix, alpha):
    return (pfm_matrix+alpha)/(len(sites) + 4*alpha)

In [33]:
ppm_matrix = PFM_to_PPM(sites, pfm_matrix, 0.1)
ppm_matrix

array([[0.10576923, 0.77884615, 0.10576923, 0.00961538, 0.00961538,
        0.20192308, 0.68269231, 0.20192308, 0.10576923],
       [0.20192308, 0.00961538, 0.00961538, 0.00961538, 0.97115385,
        0.20192308, 0.00961538, 0.00961538, 0.10576923],
       [0.10576923, 0.00961538, 0.77884615, 0.97115385, 0.00961538,
        0.00961538, 0.29807692, 0.77884615, 0.00961538],
       [0.58653846, 0.20192308, 0.10576923, 0.00961538, 0.00961538,
        0.58653846, 0.00961538, 0.00961538, 0.77884615]])

In [35]:
def PPM_to_PWM(ppm_matrix, probabilities):
    return np.log2(ppm_matrix / probabilities[:, np.newaxis])

In [37]:
pwm_matrix = PPM_to_PWM(ppm_matrix, np.array([0.295, 0.295, 0.205, 0.205]))
pwm_matrix

array([[-1.47979496,  1.40062343, -1.47979496, -4.93922658, -4.93922658,
        -0.54690915,  1.21052054, -0.54690915, -1.47979496],
       [-0.54690915, -4.93922658, -4.93922658, -4.93922658,  1.71898491,
        -0.54690915, -4.93922658, -4.93922658, -1.47979496],
       [-0.95470391, -4.41413553,  1.92571447,  2.24407595, -4.41413553,
        -4.41413553,  0.54006078,  1.92571447, -4.41413553],
       [ 1.5166018 , -0.02181811, -0.95470391, -4.41413553, -4.41413553,
         1.5166018 , -4.41413553, -4.41413553,  1.92571447]])

In [39]:
nucleotides = ['A', 'T', 'G', 'C']

max_indices = np.argmax(pwm_matrix, axis=0)
min_indices = np.argmin(pwm_matrix, axis=0)

max_seq = ''.join(nucleotides[i] for i in max_indices)
min_seq = ''.join(nucleotides[i] for i in min_indices)

max_score = np.sum(pwm_matrix[max_indices, range(pwm_matrix.shape[1])])
min_score = np.sum(pwm_matrix[min_indices, range(pwm_matrix.shape[1])])

print(f"Максимальный скор: {max_score:.4f}")
print(f"Последовательность: {max_seq}")
print(f"Минимальный скор: {min_score:.4f}")
print(f"Последовательность: {min_seq}")

Максимальный скор: 15.3846
Последовательность: CAGGTCAGC
Минимальный скор: -39.9434
Последовательность: ATTAAGTTG
