### Задание 9. 

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [209]:
from Bio import SeqIO
record = SeqIO.read ("/Users/arina.anurieva/Downloads/chr1.fa", "fasta")
seq_real = str(record.seq)[:5000].upper()    # если брать больше нуклеотидов то p-value становится меньше компьютерного нуля

In [210]:
nuc_count = {'A': 0, 'T': 0, 'G': 0, 'C': 0}
for i in range(len(seq_real)):
    nuc_count[seq_real[i]] += 1

In [211]:
probs = np.array(list(nuc_count.values()))/len(seq_real)
seq_random = ''.join(np.random.choice(['A', 'T', 'G', 'C'], size=len(seq_real), p=probs))

In [212]:
O_freq = np.zeros((4,4), dtype=int)
nuc_to_idx = {'A':0, 'C':1, 'G':2, 'T':3}

for k in range(len(seq_real)-1):
    i = nuc_to_idx[seq_real[k]]
    j = nuc_to_idx[seq_real[k+1]]
    O_freq[i,j] += 1

In [213]:
print(f"Матрица частот: \n{O_freq}")

Матрица частот: 
[[256 274 363 136]
 [338 625 165 454]
 [262 410 419 241]
 [173 274 385 224]]


In [214]:
E_freq = np.zeros((4,4), dtype=int)
idx_to_nuc = {0:'A', 1:'C', 2:'G', 3:'T'}

for i in range(4):
    prob_i = nuc_count[idx_to_nuc[i]]/len(seq_real)
    for j in range(4):
        prob_j = nuc_count[idx_to_nuc[j]]/len(seq_real)
        E_freq[i, j] = prob_i*prob_j*len(seq_real)

In [221]:
print(f"Матрица ожидаемых частот: \n{E_freq}")

Матрица ожидаемых частот: 
[[211 325 274 217]
 [325 501 421 334]
 [274 421 354 281]
 [217 334 281 223]]


In [223]:
from scipy.stats import chi2

chi_2 = np.sum((O_freq - E_freq)**2 / E_freq)
p_value = chi2.sf(chi_2, 9)

print(f"Значение хи-квадрат {chi_2.round(3)}, p-value = {p_value}")

Значение хи-квадрат 383.373, p-value = 4.818287283812806e-77


**Вывод:** значение p-value меньше 0.05 — отвергаем гипотезу, нужна марковская цепь первого порядка.